apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-dns-lb 
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: udp
    protocol: UDP
    port: 53
    targetPort: 53
  externalIPs:
    - 172.17.255.10
