server:  
  standalone:
    enabled: false

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: angular-pursuit-275120
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/gcp_sa.json

  extraVolumes:
    - type: 'secret'
      name: 'kms-creds'

  ha:
    enabled: true

    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      seal "gcpckms" {
        project     = "angular-pursuit-275120"
        region      = "global"
        key_ring    = "vault"
        crypto_key  = "vault"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

ui:
  enabled: true
