apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: vaultcsr
spec:
  groups:
  - system:authenticated
  request: $(base64 < "vault.csr" | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
