apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentservice
  name: paymentservice
spec:
  replicas: 10
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: darkdance/paymentservice:v0.0.1
        resources: {}
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
      dnsPolicy: ClusterFirst
status: {}
