apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend-healthy
  name: frontend-healthy
spec:
  containers:
  - image: darkdance/frontend
    name: frontend-healthy
    resources: {}
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice:3550"
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice:7000"
    - name: CART_SERVICE_ADDR
      value: "currencyservice:7000"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendationservice:8080"
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice:50051"
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkoutservice:5050"
    - name: AD_SERVICE_ADDR
      value: "adservice:9555"
    - name: ENABLE_PROFILER
      value: "0"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
